### ISSUE TITLE
container options

### ISSUE THREAD

**Issue by onursonmez** [benitolopez/hotel-datepicker#1]
Would you please show me an example?

**Comment by benitolopez** [comment]
Hi,

The option sets the container of the datepicker. If you don't pass it, the parent of the input is used instead. It is useful to append the datepicker to a custom container.

Example:

```js
var customContainer = document.getElementById('your-container');
var datepicker = new HotelDatepicker(document.getElementById('your-input'), {
	container: customContainer
});
```

**Comment by omguddu100** [comment]
can You plz help me
![image](https://user-images.githubusercontent.com/16487240/30910904-3c9cf83e-a3a4-11e7-9577-7dcc599c986a.png)

I added customContainer but also getting same error
` var input1 = document.getElementById('ppzdate');
        var containery = document.getElementById('yyyyy');
        hdpkr = new HotelDatepicker(input1, {
            format: 'DD-MM-YYYY',
            autoClose: false,
            container: containery,
            disabledDates: dynamicdates,

        });
        hdpkr.open();
        hdpkr.init();
       
    });`

![image](https://user-images.githubusercontent.com/16487240/30911030-9c4e889c-a3a4-11e7-9f42-f380df46099b.png)
input.parentElement is getting null

**Comment by benitolopez** [comment]
Just tried and it works. No error. Can I see your page? 
That error means that your input doesn't exist. Are you using the correct id for the input (ppzdate)?

Also, why are you calling the `init()` function? That's an internal function. You should use only the `open()` function.

**Comment by omguddu100** [comment]
Yes Sir i using correct id,
![image](https://user-images.githubusercontent.com/16487240/30914258-aacb5ad8-a3b0-11e7-84e7-10971bc6e76a.png)
 I makes changes now code is:
`
        var hdpkr;
        var dynamicdates = [
               '2017-09-27',
               '2017-09-23',
               '2017-09-26',
               '2017-09-28',
               '2017-10-01',
               '2017-10-11'
        ]

        var input = document.getElementById('ppzdate');
        var containery = document.getElementById('yyyyy');
        hdpkr = new HotelDatepicker(input, {
            format: 'DD-MM-YYYY',
            autoClose: false,
            container: containery,
            disabledDates: dynamicdates,

        });
        hdpkr.open();`


Note: but datepicker is showing correctly & working find also, but getting same error
![image](https://user-images.githubusercontent.com/16487240/30914551-b6afbd02-a3b1-11e7-963a-29f9b8c19bc4.png)

I don't know it will make conflict or not others codes in future.

**Comment by Cristiano81** [comment]
Hi,have you placed the initialization of datepicker inside a document ready function?


----Messaggio originale----

Da: notifications@github.com

Data: 27-set-2017 15.06

A: "benitolopez/hotel-datepicker"<hotel-datepicker@noreply.github.com>

Cc: "Subscribed"<subscribed@noreply.github.com>

Ogg: Re: [benitolopez/hotel-datepicker] container options (#1)




Yes Sir i using correct id,



I makes changes now code is:

`

var hdpkr;

var dynamicdates = [

'2017-09-27',

'2017-09-23',

'2017-09-26',

'2017-09-28',

'2017-10-01',

'2017-10-11'

]
    var input = document.getElementById('ppzdate');
    var containery = document.getElementById('yyyyy');
    hdpkr = new HotelDatepicker(input, {
        format: 'DD-MM-YYYY',
        autoClose: false,
        container: containery,
        disabledDates: dynamicdates,

    });
    hdpkr.open();`


Note: but datepicker is showing correctly &amp; working find also, but getting same error



I don't know it will make conflict or not others codes in future.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benitolopez/hotel-datepicker","title":"benitolopez/hotel-datepicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benitolopez/hotel-datepicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@omguddu100 in #1: Yes Sir i using correct id,\r\n![image](https://user-images.githubusercontent.com/16487240/30914258-aacb5ad8-a3b0-11e7-84e7-10971bc6e76a.png)\r\n I makes changes now code is:\r\n`\r\n        var hdpkr;\r\n        var dynamicdates = [\r\n               '2017-09-27',\r\n               '2017-09-23',\r\n               '2017-09-26',\r\n               '2017-09-28',\r\n               '2017-10-01',\r\n               '2017-10-11'\r\n        ]\r\n\r\n        var input = document.getElementById('ppzdate');\r\n        var containery = document.getElementById('yyyyy');\r\n        hdpkr = new HotelDatepicker(input, {\r\n            format: 'DD-MM-YYYY',\r\n            autoClose: false,\r\n            container: containery,\r\n            disabledDates: dynamicdates,\r\n\r\n        });\r\n        hdpkr.open();`\r\n\r\n\r\nNote: but datepicker is showing correctly \u0026 working find also, but getting same error\r\n![image](https://user-images.githubusercontent.com/16487240/30914551-b6afbd02-a3b1-11e7-963a-29f9b8c19bc4.png)\r\n\r\nI don't know it will make conflict or not others codes in future.  \r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/benitolopez/hotel-datepicker/issues/1#issuecomment-332514155"}}}

**Comment by benitolopez** [comment]
Are you using a custom version of the plugin? Can you make your tests with the default and unmodified hotel-datepicker.js file?

And again, a real URL would be much appreciated.

**Comment by omguddu100** [comment]
@Cristiano81 . No, when i initialization inside document ready function, then it not working so I initialize without  document ready function . Thanks

**Comment by omguddu100** [comment]
Yes sir I customized only for 'always show datepicker'. sure i will test  my custom plugin with  hotel-datepicker.js. 
thanks for valuable support.!

**Comment by Cristiano81** [comment]
what error do you get from document ready?




----Messaggio originale----

Da: notifications@github.com

Data: 27-set-2017 15.32

A: "benitolopez/hotel-datepicker"<hotel-datepicker@noreply.github.com>

Cc: "Cristiano Nerozzi"<cristiano.nerozzi@alice.it>, "Mention"<mention@noreply.github.com>

Ogg: Re: [benitolopez/hotel-datepicker] container options (#1)




@Cristiano81 . No, when i initialization inside document ready function, then it not working so I initialize without  document ready function . Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benitolopez/hotel-datepicker","title":"benitolopez/hotel-datepicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benitolopez/hotel-datepicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@omguddu100 in #1: @Cristiano81 . No, when i initialization inside document ready function, then it not working so I initialize without  document ready function . Thanks"}],"action":{"name":"View Issue","url":"https://github.com/benitolopez/hotel-datepicker/issues/1#issuecomment-332521703"}}}

**Comment by omguddu100** [comment]
@Cristiano81 datepicker not showing & getting thing 
![image](https://user-images.githubusercontent.com/16487240/30919428-fb5d7cfc-a3be-11e7-8214-640b9ffabbff.png)

**Comment by Cristiano81** [comment]
as benito said, if you could provide the page link , we can help you


----Messaggio originale----

Da: notifications@github.com

Data: 27-set-2017 16.33

A: "benitolopez/hotel-datepicker"<hotel-datepicker@noreply.github.com>

Cc: "Cristiano Nerozzi"<cristiano.nerozzi@alice.it>, "Mention"<mention@noreply.github.com>

Ogg: Re: [benitolopez/hotel-datepicker] container options (#1)




@Cristiano81 datepicker not showing &amp; getting thing



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benitolopez/hotel-datepicker","title":"benitolopez/hotel-datepicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benitolopez/hotel-datepicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@omguddu100 in #1: @Cristiano81 datepicker not showing \u0026 getting thing \r\n![image](https://user-images.githubusercontent.com/16487240/30919428-fb5d7cfc-a3be-11e7-8214-640b9ffabbff.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/benitolopez/hotel-datepicker/issues/1#issuecomment-332541519"}}}

**Comment by omguddu100** [comment]
It's working  on in my company local machine. so not possible to share link. trying to fix myself.
