### ISSUE TITLE
invalid day without reason

### ISSUE THREAD

**Issue by cynat** [benitolopez/hotel-datepicker#107]
issue occurs for specific day 26th of march when disabledDates = ['2022-03-25','2022-03-27']

**Comment by benitolopez** [comment]
Hello,

You can't select 26th of march if the days before and after are disabled. This is a date range picker, so a valid selection requires at least 2 days. On 26th of march you don't a day available before or after.

**Comment by cynat** [comment]
Hi and thanks for this quick answer. But why is it working eg. when disabledDates = ['2022-03-18','2022-03-20'] where  you can select 1 night ?

**Comment by benitolopez** [comment]
Do you have `enableCheckout` set to true? You can select the date between those dates only in that case.

But I see that you can't select 26th of march when `enableCheckout` is set to true. This is probably a DST issue because at least in my town there will be a daylight saving time change on 27th of march.

I need some time to investigate the issue, it won't be solved immediately. DST issues are a tricky.

**Comment by benitolopez** [comment]
Version 4.0.3 should solve the issue
