### ISSUE TITLE
Add the clearButton to the drop-down implementation

### ISSUE THREAD

**Issue by eli-pritykin** [benitolopez/hotel-datepicker#142]
Currently, this button is only available for inline views. We'd love to have this available in drop-down implementation as well.

Please and thank you :)

**Comment by benitolopez** [comment]
Yes, this is something that can be considered. For the inline version a clear button was mandatory because otherwise you can't clear the dates. With the dropdown version you can still delete the value of the input to clear the dates. But I agree, it can be helpful for the dropdown version too. 

The problem is that I'm really busy right now so I can't anticipate any date.

**Comment by eli-pritykin** [comment]
Understood. Not a problem. Thank you for considering it. Feel free to close this issue if you like.

**Comment by benitolopez** [comment]
It is now possibile with the version 4.5.0

**Comment by eli-pritykin** [comment]
amazing, thank you!
