### ISSUE TITLE
Datepicker is invisible after disabling the input

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#159]
In this case the when choosing Buy I manually disable the input with jQuery. After enabling it again the datepicker has datepicker--open class, but inline styles adds `height:0` and due to it it's invisible. I can manually fix it by adding a css class:

```
    #datepicker-dates.datepicker--open {
      height: auto !important;
    }
``` 

But I will loose the smooth fade-in transition.

In action:

https://user-images.githubusercontent.com/46891372/218471370-e37dc45d-9236-4570-b666-0850b02d8be5.mp4

**Comment by 3nematix** [comment]
```
 <input size="21" autocomplete="off" id="dates" name="f.s-reservation-date" placeholder="Select Reservation Dates..." class="min-w-full text-primary font-semibold text-lg mt-0.5 outline-none bg-transparent">

 $("#dates").attr("disabled", true);
 ```

**Comment by 3nematix** [comment]
Also I wanted to ask why the arrows are not visible? Am I missing anything?

By default these styles are being applied, do I need to change it?

```
.datepicker__month-button--next::after {
    background-image: url(../icons/right.svg);
}
```

**Comment by benitolopez** [comment]
Hello,

Sorry but this is something you need to fix by yourself because the issue is caused by the way your custom code interacts with the input. Maybe try to close the datepicker when you click on the Buy button:
https://github.com/benitolopez/hotel-datepicker#close

Or just hide the datepicker with CSS instead of disabling the input.

Regarding the second question, you don't need to change the CSS. It should work out of the box. If it doesn't work, try to open the browser inspector to see if there are errors.

You must have the icons folder in the same root folder as the css folder. Like this:
https://lopezb.d.pr/i/K0R6jU

Best,
Benito
