### ISSUE TITLE
Reset calendar after destroy?

### ISSUE THREAD

**Issue by arsistyle** [benitolopez/hotel-datepicker#29]
how i cand reset selected dates and other options when destroy?

**Comment by benitolopez** [comment]
Hi,

You can use the `destroy` method to destroy the datepicker. See the demo and the readme:
https://github.com/benitolopez/hotel-datepicker#destroy

Then to clear the input just use Javascript (when you call the `destroy` method).

**Comment by arsistyle** [comment]
No, i dont need clear the input, i need to clear the classes and options from the datepicker. The question is: can i do that?

**Comment by benitolopez** [comment]
Sorry but I don't understand: what classes and options? The selected dates? You need to clear the input to clear the selected dates. Because when the input has a value, the datepicker uses that value to show the selected dates.

So you can't have an input with a value and the datepicker without selected dates at the same time.

**Comment by thekendog** [comment]
I think what he means is can you reload the options and reinitialize the picker after a destroy?  For instance, I'm loading disabled dates with an ajax function and I then need to disable those dates on the calendar.  Is there a built in way to do this?

**Comment by benitolopez** [comment]
Hi,

No there's not any built in option, you need to reinitialize the datepicker again. Just save the options in a variable and reuse it.
