### ISSUE TITLE
Set Range not working for specific dates.

### ISSUE THREAD

**Issue by beezischillin** [benitolopez/hotel-datepicker#59]
Hi, pretty great plugin! I'm unfortunately having some issues with it right now!

If I call something like .setRange( '2018-10-27', '2018-11-01' ); then the whole calendar resets and the range doesn't get applied. This seems to happen to some date ranges but not others. I'm not able to select anything up to 11-04 but .setRange( '2018-10-27', '2018-11-05' ); works.

Do you have any idea why this is happening?

From what I can tell valid does not get set to false in your setRange function

**Comment by beezischillin** [comment]
Also, strangely enough this issue only seems to occur when you try and select a range that starts at the end of an October. Same issue happens if I do it for 2019 October. I scrolled through every month, checking for it in 2019 and only October seems to bug out.

**Comment by benitolopez** [comment]
Hi,

Tried right now with the same dates and it works without any issues. Please share the URL of your page so I can see your code.

**Comment by beezischillin** [comment]
[Archive.zip](https://github.com/benitolopez/hotel-datepicker/files/2435642/Archive.zip)

Thank you for getting back to me so quickly. I attached an example html where the issue can be reproduced. Try clicking on the 27th or 28th of October.

**Comment by benitolopez** [comment]
Using 6 for max nights (and 5 for min nights) should solve the issue. I think that it is happening in that particular date because of the daylight saving time, that ends that week (2018-10-28).

Javascript dates and DST are tricky. I don't know if I will be able to find a solution. I've already fixed a similar issue related to that long time ago (https://github.com/benitolopez/hotel-datepicker/issues/2). I will try in my spare time. But again, just use 6 for max nights.

**Comment by beezischillin** [comment]
Thank you for the info! 

Can you please add it to the readme? That would probably be the best short term solution.

**Comment by benitolopez** [comment]
It should be fixed now on the version 3.6.5 (https://github.com/benitolopez/hotel-datepicker/commit/2887a00f763c2f0c87324cda98a8cb8880ee1897).
