### ISSUE TITLE
How to always show in div. 

### ISSUE THREAD

**Issue by omguddu100** [benitolopez/hotel-datepicker#6]
Hi,
Is posssible to always show datepicker like container, wihtout input tag.

**Comment by Cristiano81** [comment]
Hi,this is how i did it:
1. place in html an input type text with style display none:<input type="text" id="xxxxx" style="display:none" /><div id="yyyyy"></div>
2. on document ready open the hoteldatepicker with autoclose false:var hdpkr;$(document).ready(function () { var input = document.getElementById('xxxxx'); var containery = document.getElementById('yyyyy'); hdpkr = new HotelDatepicker(input, {  container: containery,  autoClose: false });  hdpkr.open();});
3. alway return on closeDatepicker functionHotelDatepicker.prototype.closeDatepicker = function closeDatepicker () {        // Close the datepicker		//never close	//if (!this.isOpen) {		return;	//}
        // Add/remove helper classes	this.removeClass(this.datepicker, 'datepicker--open');	this.addClass(this.datepicker, 'datepicker--closed');
        // Slide up the datepicker	this.slideUp(this.datepicker, this.animationSpeed);	this.isOpen = false;};
and this is the result:
https://www.emmavillas.com/en/countryside-villas/tuscany/casale-la-splendida-10/availability.aspx
bye bye


----Messaggio originale----

Da: notifications@github.com

Data: 20-set-2017 8.31

A: "benitolopez/hotel-datepicker"<hotel-datepicker@noreply.github.com>

Cc: "Subscribed"<subscribed@noreply.github.com>

Ogg: [benitolopez/hotel-datepicker] How to always show in div. (#6)




Hi,

Is posssible to always show datepicker like container, wihtout input tag.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benitolopez/hotel-datepicker","title":"benitolopez/hotel-datepicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benitolopez/hotel-datepicker"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How to always show in div.  (#6)"}],"action":{"name":"View Issue","url":"https://github.com/benitolopez/hotel-datepicker/issues/6"}}}

**Comment by benitolopez** [comment]
Yes, you should init the datepicker with autoclose false. Then use some CSS to hide the input.

**Comment by omguddu100** [comment]
Thanks a lot !
