### ISSUE TITLE
Api OPEN

### ISSUE THREAD

**Issue by 4uva4ok1905** [benitolopez/hotel-datepicker#83]
If custom btn parent not have input  - datepicker not working

http://prntscr.com/s1ptpc

` if (!this.parent.contains(evt.target) && evt.target !== this.input) {`

**Comment by benitolopez** [comment]
Hi,

Yes, it is by design. The datepicker autocloses when you click outside of its container, it is not a bug.

You can prevent it passing a custom container and insert the input and the button inside it:

```js
var hdpkr = new HotelDatepicker(document.getElementById('input-id'), {
    container: document.getElementById('your-wrapper')
});
```

Anyway, considering that this is the second time someone reports this problem, I've added a new option `preventContainerClose`: setting it to true, you will disable that behavior. Available in the version 3.7.0.

Hope this helps.
